backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

slug:
  encoding: "ascii"
  clean_accents: true

  # These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Nadpis", name: "title", widget: "string"}
      - {label: "Pořadí", name: "weight", widget: "number", default: 100, valueType: int, min: 1, max: 1000}
      - {label: "Koncept", name: "draft", widget: "boolean", default: true}
      - {label: "Štítky", name: "tags", widget: "list", default: []}
      - label: "Cover"
        name: "cover"
        widget: "object"
        fields:
          - {label: "Obrázek", name: "image", widget: "image", required: false}
          - {label: "Schovaný", name: "hidden", widget: "boolean", default: false}
      - {label: "Text", name: "body", widget: "markdown"}     
  - name: "single-pages" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Jednotlivé stránky" # Used in the UI, ie.: "New Post"
    files:  
      - file: "content/about.md"
        label: "O nás"
        name: "about"
        fields: # The fields for each document, usually in front matter
          - {label: "Nadpis", name: "title", widget: "string"}
          - {label: "Koncept", name: "draft", widget: "boolean", default: false}
          - label: "Cover"
            name: "cover"
            widget: "object"
            fields:
              - {label: "Obrázek", name: "image", widget: "image", required: false}
              - {label: "Schovaný", name: "hidden", widget: "boolean", default: false}
          - {label: "Text", name: "body", widget: "markdown"}